banner:
  charset: UTF-8
  location: classpath:banner.txt

server:
       error:
             whitelabel:
                       enabled: false


       context-path: /utez
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ferreteria
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: update
  
        